const OPENAI_TTS_VOICES=['alloy','ash','ballad','coral','echo','fable','onyx','nova','sage','shimmer','verse','marin','cedar'];

function emptyAudioModel(){return {schemaVersion:1,voices:[],voiceReferences:[],dialogues:[],takes:[],musicCues:[],soundEffects:[],ambience:[],seedanceReferences:[],settings:{provider:'openai',model:'gpt-4o-mini-tts',format:'wav'}};}

function ensureAudioModel(p,seed=false){
  p.audio=p.audio&&typeof p.audio==='object'?p.audio:emptyAudioModel();
  (p.assets||[]).filter(asset=>asset.type==='音频').forEach(asset=>{asset.skill='audio';});
  const base=emptyAudioModel();Object.keys(base).forEach(k=>{if(p.audio[k]===undefined)p.audio[k]=base[k];});
  if(seed&&!p.audio.voices.length){
    p.audio.voices.push({id:'V001',name:'明天的林夏',sourceType:'preset',provider:'openai',model:'gpt-4o-mini-tts',providerVoiceId:'coral',language:'zh-CN',dialect:'普通话',traits:'克制、低声、带轻微疲惫感',consentStatus:'not-required',licenseStatus:'cleared',status:'provisional'});
    p.audio.dialogues.push({id:'DLG001',characterId:'C001',voiceId:'V001',shotIds:['SH002'],text:'不要开门。',language:'zh-CN',emotion:'冷静但急迫',intensity:'中等',pace:0.92,targetDuration:2.2,pronunciation:'',selectedTakeId:null,status:'planned'});
    p.audio.musicCues.push({id:'CUE001',musicId:'MUS001',shotIds:['SH001','SH002','SH003','SH004','SH005','SH006'],start:0,end:28,purpose:'低频悬疑氛围，逐步收紧但不遮挡对白',entry:'雨声中淡入',exit:'录音键按下时切断',dialogueAvoidance:['DLG001'],loopable:false,filePath:'',licenseStatus:'pending',qaDecision:'',status:'planned'});
  }
  return p.audio;
}

function nextAudioId(items,prefix){let max=0;items.forEach(x=>{const m=String(x.id||'').match(new RegExp(`^${prefix}(\\d+)$`));if(m)max=Math.max(max,+m[1]);});return `${prefix}${String(max+1).padStart(3,'0')}`;}
function audioApproved(x){return ['approved','ready'].includes(x.status)&&(!x.qaDecision||x.qaDecision==='Approved'||x.qa?.decision==='Approved');}
function audioSummary(p){const a=ensureAudioModel(p),all=[...a.voices,...a.dialogues,...a.takes,...a.musicCues,...a.soundEffects,...a.ambience],approved=all.filter(audioApproved).length,blocked=all.filter(x=>['blocked','rejected','pending-consent'].includes(x.status)||['pending-consent','restricted','rejected'].includes(x.consentStatus)).length,openItems=all.filter(x=>!audioApproved(x)).length;return {total:all.length,approved,blocked,openItems,readiness:all.length>0&&openItems===0?'ready':blocked?'blocked':'partial'};}
function audioTaskSummary(p){const a=ensureAudioModel(p),s=audioSummary(p);return `声音 ${a.voices.length}；参考音 ${a.voiceReferences.length}；对白 ${a.dialogues.length}；Take ${a.takes.length}；配乐 Cue ${a.musicCues.length}；就绪 ${s.approved}/${s.total}；阻塞 ${s.blocked}`;}
function audioMarkdown(p){const a=ensureAudioModel(p),s=audioSummary(p);return [`- 音频总状态：${s.readiness}`,...a.voices.map(v=>`- ${v.id} ${v.name}｜${v.sourceType}｜${statusLabel(v.status)}｜授权 ${v.consentStatus}`),...a.dialogues.map(d=>`- ${d.id}「${d.text}」｜${d.shotIds.join(', ')}｜${d.selectedTakeId||'未选择 Take'}｜${statusLabel(d.status)}`),...a.musicCues.map(c=>`- ${c.id} ${c.start}-${c.end}s｜${c.purpose}｜版权 ${c.licenseStatus}｜${statusLabel(c.status)}`)].join('\n');}

function audioStatusChip(value){return `<span class="audio-chip ${esc(value)}">${esc(statusLabel(value))}</span>`;}
function voiceOptions(p,selected=''){return ensureAudioModel(p).voices.map(v=>`<option value="${v.id}" ${v.id===selected?'selected':''}>${v.id} · ${esc(v.name)}</option>`).join('');}
function shotChecks(p,selected=[]){return p.shots.map(s=>`<label class="check-card"><input type="checkbox" name="shotIds" value="${s.id}" ${selected.includes(s.id)?'checked':''}><span><b>${s.id}</b><small>${esc(s.purpose)}</small></span></label>`).join('')||'<span class="subtle">暂无镜头</span>';}

function renderAudio(p){
  const a=ensureAudioModel(p),summary=audioSummary(p);
  return `${pageHead('VOICE CONTROLLER','配音与声音','在这里完成声音选角、授权、逐句 Take、配乐 Cue、音频 QA 和镜头交接。',`<button class="primary" id="voiceSkillTask">复制 Voice Controller 任务</button>`)}
  <section class="stats audio-stats"><div class="stat"><span>声音资产</span><strong>${a.voices.length}</strong><small>${a.voiceReferences.length} 个参考声音</small></div><div class="stat" style="--glow:var(--cyan)"><span>对白 / Take</span><strong>${a.dialogues.length}/${a.takes.length}</strong><small>逐句生成，不覆盖批准版本</small></div><div class="stat" style="--glow:var(--violet)"><span>配乐 Cue</span><strong>${a.musicCues.length}</strong><small>对白避让与版权状态</small></div><div class="stat" style="--glow:var(--orange)"><span>声音就绪</span><strong>${summary.approved}/${summary.total}</strong><small>${summary.blocked} 项阻塞 · ${statusLabel(summary.readiness)}</small></div></section>
  <section class="panel audio-gate"><div class="panel-head"><h3>两阶段声音流程</h3><span>Voice Controller Gate</span></div><div class="audio-flow"><div><b>01 剧本锁定</b><span>提取对白、选角、参考声音和三段试音</span></div><i>→</i><div><b>02 授权门禁</b><span>克隆与表演迁移必须验证同意和来源</span></div><i>→</i><div><b>03 镜头定时</b><span>镜头导演锁定时长、情绪和声桥</span></div><i>→</i><div><b>04 正式交付</b><span>逐句 Take、配乐 Cue、QA、@Audio 映射</span></div></div></section>
  <div class="audio-layout">
    <section class="audio-main">
      ${renderVoiceLibrary(p)}
      ${renderDialogueDesk(p)}
      ${renderMusicDesk(p)}
    </section>
    <aside class="audio-side">
      ${renderAudioExecution(p)}
      ${renderAudioHandoff(p)}
    </aside>
  </div>`;
}

function renderVoiceLibrary(p){const a=p.audio;return `<section class="panel"><div class="panel-head"><h3>声音资产库</h3><div class="toolbar"><button class="mini-button" id="addVoice">＋ 声音</button><button class="mini-button" id="importVoiceRef">上传参考声音</button><input id="voiceRefFile" type="file" accept="audio/*" hidden></div></div><div class="audio-cards">${a.voices.map(v=>`<article class="audio-card"><header><div><strong>${v.id} · ${esc(v.name)}</strong><small>${esc(v.provider||'未选供应商')} / ${esc(v.providerVoiceId||v.sourceType)}</small></div>${audioStatusChip(v.status)}</header><p>${esc(v.traits||'尚未定义声音特征')}</p><footer><span>来源 ${esc(v.sourceType)}</span><span>授权 ${esc(v.consentStatus)}</span><button class="link-button" data-audio-approve="voice" data-id="${v.id}">${audioApproved(v)?'已锁定':'锁定声音'}</button></footer></article>`).join('')||'<div class="empty compact">尚无角色声音。先创建预设声音或登记授权参考。</div>'}</div><div class="reference-strip">${a.voiceReferences.map(r=>`<div class="reference-file"><div><b>${r.id} · ${esc(r.name)}</b><small>${esc(r.duration||'未分析')} · ${esc(r.sourceClass)}</small></div>${audioStatusChip(r.consentStatus)}</div>`).join('')||'<span class="subtle">暂无参考声音。文件上传仅保存到本机；调用外部克隆服务前仍需再次确认。</span>'}</div></section>`;}

function renderDialogueDesk(p){const a=p.audio;return `<section class="panel"><div class="panel-head"><h3>对白与 Take</h3><button class="mini-button" id="addDialogue">＋ 登记对白</button></div><div class="dialogue-list">${a.dialogues.map(d=>{const takes=a.takes.filter(t=>t.dialogueId===d.id);return `<article class="dialogue-row"><div class="dialogue-copy"><div><b>${d.id}</b>${audioStatusChip(d.status)}<small>${esc(d.shotIds.join(', '))} · ${esc(d.emotion)} · 目标 ${d.targetDuration||'—'}s</small></div><p>“${esc(d.text)}”</p><span>${esc(d.voiceId)} · 语速 ${esc(d.pace||1)} · ${takes.length} 个 Take</span></div><div class="take-stack">${takes.map(t=>`<div class="take-item ${d.selectedTakeId===t.id?'selected':''}"><div><b>${t.id} · v${String(t.version).padStart(2,'0')}</b><small>${esc(t.provider)} / ${esc(t.model)} · ${t.duration?`${t.duration}s`:'待测时长'}</small></div>${t.filePath?`<audio controls preload="none" src="${esc(t.filePath)}"></audio>`:''}<div class="take-actions">${audioStatusChip(t.status)}<button class="link-button" data-select-take="${t.id}" data-dialogue="${d.id}">${d.selectedTakeId===t.id?'已选择':'选择 Take'}</button><button class="link-button" data-approve-take="${t.id}">${audioApproved(t)?'QA 已通过':'通过 QA'}</button></div></div>`).join('')||'<span class="subtle">尚无 Take；在右侧生成试听，或导入外部结果。</span>'}</div><button class="mini-button dialogue-generate" data-generate-dialogue="${d.id}">生成试听</button></article>`}).join('')||'<div class="empty compact">尚无对白。可从脚本提取后登记，或手动添加第一句。</div>'}</div></section>`;}

function renderMusicDesk(p){const cues=p.audio.musicCues;return `<section class="panel"><div class="panel-head"><h3>配乐 Cue 与声音设计</h3><button class="mini-button" id="addMusicCue">＋ 配乐 Cue</button></div><div class="cue-table"><div class="cue-head"><span>ID / 镜头</span><span>时间</span><span>叙事作用</span><span>版权 / QA</span></div>${cues.map(c=>`<div class="cue-row"><div><b>${c.id}</b><small>${esc(c.shotIds.join(', '))}</small></div><span>${c.start}–${c.end}s</span><div><b>${esc(c.purpose)}</b><small>${esc(c.entry)} → ${esc(c.exit)}</small></div><div>${audioStatusChip(c.licenseStatus)}<button class="link-button" data-approve-cue="${c.id}">${audioApproved(c)?'已批准':'通过 QA'}</button></div></div>`).join('')||'<div class="empty compact">尚无音乐 Cue。</div>'}</div></section>`;}

function renderAudioExecution(p){const a=p.audio,s=a.settings;return `<section class="panel sticky-card"><div class="panel-head"><h3>试听生成</h3><span>OpenAI 本地代理</span></div><div class="panel-body"><div class="field"><label for="ttsDialogue">对白</label><select id="ttsDialogue">${a.dialogues.map(d=>`<option value="${d.id}">${d.id} · ${esc(d.text.slice(0,22))}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label for="ttsModel">模型</label><input id="ttsModel" value="${esc(s.model)}" readonly></div><div class="field"><label for="ttsVoice">内置声音</label><select id="ttsVoice">${OPENAI_TTS_VOICES.map(v=>`<option ${v==='coral'?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label for="ttsInstructions">表演指令</label><textarea id="ttsInstructions">低声、克制，急迫感藏在短停顿里；普通话自然口语，不要广告播音腔。</textarea></div><div class="form-grid"><div class="field"><label for="ttsSpeed">速度</label><input id="ttsSpeed" type="number" min="0.25" max="4" step="0.05" value="0.95"></div><div class="field"><label for="ttsFormat">格式</label><select id="ttsFormat"><option>wav</option><option>mp3</option><option>flac</option><option>aac</option><option>opus</option></select></div></div><label class="execution-confirm"><input type="checkbox" id="ttsConfirmed"><span><b>确认调用付费外部服务</b><small>对白文本将发送给 OpenAI；API Key 只在本地服务端读取。</small></span></label><button class="primary full" id="generateTts" ${a.dialogues.length?'':'disabled'}>生成新 Take</button><p class="generation-status" id="ttsStatus">不勾选确认框时不会发送请求或产生费用。</p></div></section>`;}

function renderAudioHandoff(p){const a=p.audio,s=audioSummary(p);return `<section class="panel"><div class="panel-head"><h3>交接与门禁</h3><span>${statusLabel(s.readiness)}</span></div><div class="panel-body"><div class="gate-row"><span>声音授权</span><b>${a.voices.every(v=>['not-required','consent-verified'].includes(v.consentStatus))?'通过':'待处理'}</b></div><div class="gate-row"><span>对白已选 Take</span><b>${a.dialogues.every(d=>d.selectedTakeId)?'通过':'待处理'}</b></div><div class="gate-row"><span>配乐版权</span><b>${a.musicCues.every(c=>['cleared','not-required'].includes(c.licenseStatus))?'通过':'待处理'}</b></div><div class="gate-row"><span>音频 QA</span><b>${s.readiness==='ready'?'通过':'待处理'}</b></div><div class="audio-handoff-map">${a.seedanceReferences.map(r=>`<div><b>${r.token}</b><span>${esc(r.assetId)} · ${esc(r.role)}</span></div>`).join('')||'<span class="subtle">批准并选择 Take 后生成 @Audio 映射。</span>'}</div><button class="ghost full" id="buildAudioHandoff">重建 @Audio 映射</button><button class="ghost full" id="exportAudioPackage">导出音频生产包 JSON</button></div></section>`;}

function bindAudioView(){
  document.getElementById('voiceSkillTask')?.addEventListener('click',()=>copySkillTask('audio'));
  document.getElementById('addVoice')?.addEventListener('click',addVoiceAsset);
  document.getElementById('importVoiceRef')?.addEventListener('click',()=>document.getElementById('voiceRefFile').click());
  document.getElementById('voiceRefFile')?.addEventListener('change',importVoiceReference);
  document.getElementById('addDialogue')?.addEventListener('click',addDialogueAsset);
  document.getElementById('addMusicCue')?.addEventListener('click',addMusicCue);
  document.getElementById('generateTts')?.addEventListener('click',generateTtsTake);
  document.querySelectorAll('[data-generate-dialogue]').forEach(b=>b.onclick=()=>{document.getElementById('ttsDialogue').value=b.dataset.generateDialogue;document.getElementById('ttsDialogue').scrollIntoView({behavior:'smooth',block:'center'});});
  document.querySelectorAll('[data-audio-approve="voice"]').forEach(b=>b.onclick=()=>approveVoice(b.dataset.id));
  document.querySelectorAll('[data-select-take]').forEach(b=>b.onclick=()=>selectTake(b.dataset.dialogue,b.dataset.selectTake));
  document.querySelectorAll('[data-approve-take]').forEach(b=>b.onclick=()=>approveTake(b.dataset.approveTake));
  document.querySelectorAll('[data-approve-cue]').forEach(b=>b.onclick=()=>approveCue(b.dataset.approveCue));
  document.getElementById('buildAudioHandoff')?.addEventListener('click',buildAudioHandoff);
  document.getElementById('exportAudioPackage')?.addEventListener('click',exportAudioPackage);
}

function addVoiceAsset(){const p=project(),a=p.audio,id=nextAudioId(a.voices,'V'),name=prompt('声音名称，例如“林夏旁白”');if(!name)return;const sourceType=prompt('来源类型：preset / design / clone','preset')||'preset';const needsConsent=sourceType==='clone';a.voices.push({id,name,sourceType,provider:sourceType==='preset'?'openai':'待选择',model:sourceType==='preset'?'gpt-4o-mini-tts':'',providerVoiceId:sourceType==='preset'?'coral':'',language:'zh-CN',dialect:'普通话',traits:prompt('声音特征','自然、克制、口语化')||'',consentStatus:needsConsent?'pending-consent':'not-required',licenseStatus:sourceType==='preset'?'cleared':'pending',status:needsConsent?'pending-consent':'provisional'});save();render();toast(`${id} 已登记`);}
function addDialogueAsset(){const p=project(),a=p.audio;if(!a.voices.length){toast('请先建立声音资产');return;}const text=prompt('对白文本');if(!text)return;const id=nextAudioId(a.dialogues.filter(d=>d.id.startsWith('DLG')),'DLG'),shot=p.shots[0]?.id||'';a.dialogues.push({id,characterId:'',voiceId:a.voices[0].id,shotIds:shot?[shot]:[],text,language:'zh-CN',emotion:'自然、克制',intensity:'中等',pace:1,targetDuration:3,pronunciation:'',selectedTakeId:null,status:'planned'});save();render();toast(`${id} 已登记`);}
function addMusicCue(){const p=project(),a=p.audio,id=nextAudioId(a.musicCues,'CUE'),purpose=prompt('配乐的叙事作用，例如“悬疑逐步收紧”');if(!purpose)return;a.musicCues.push({id,musicId:`MUS${String(a.musicCues.length+1).padStart(3,'0')}`,shotIds:p.shots.map(s=>s.id),start:0,end:p.duration,purpose,entry:'淡入',exit:'淡出',dialogueAvoidance:a.dialogues.map(d=>d.id),loopable:false,filePath:'',licenseStatus:'pending',qaDecision:'',status:'planned'});save();render();toast(`${id} 已登记`);}

async function importVoiceReference(e){const file=e.target.files?.[0];if(!file)return;const sourceClass=prompt('声音来源：self-owned / licensed-third-party / style-only / unknown','self-owned')||'unknown';const consent=sourceClass==='self-owned'||sourceClass==='licensed-third-party'?confirm('是否已经取得明确的声音克隆/转换授权？'):'not-authorized';const form=new FormData();form.append('file',file);try{toast('正在保存参考声音…');const response=await fetch('/api/audio/import',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||'导入失败');const a=project().audio,id=nextAudioId(a.voiceReferences,'VREF');a.voiceReferences.push({id,name:file.name,filePath:result.url,filename:result.filename,sha256:result.sha256,duration:result.duration||'',format:result.format||file.type,sourceClass,consentStatus:consent===true?'consent-supplied':sourceClass==='style-only'?'not-required':'pending-consent',status:'supplied'});save();render();toast(`${id} 已保存到本机`);}catch(error){toast(error.message);}finally{e.target.value='';}}

function approveVoice(id){const v=project().audio.voices.find(x=>x.id===id);if(!v)return;if(v.sourceType==='clone'&&v.consentStatus!=='consent-verified'){toast('克隆声音必须先验证授权');return;}v.status='approved';v.qaDecision='Approved';save();render();toast(`${id} 声音已锁定`);}
function selectTake(dialogueId,takeId){const a=project().audio,d=a.dialogues.find(x=>x.id===dialogueId),t=a.takes.find(x=>x.id===takeId);if(!d||!t)return;if(!audioApproved(t)){toast('Take 必须先通过 QA');return;}d.selectedTakeId=takeId;d.status='approved';save();render();toast(`${takeId} 已设为正式 Take`);}
function approveTake(id){const t=project().audio.takes.find(x=>x.id===id);if(!t)return;t.qa={decision:'Approved',checks:{content:true,pronunciation:true,identity:true,performance:true,timing:true,technical:true,edit:true,consent:true}};t.status='approved';save();render();toast(`${id} 已通过音频 QA`);}
function approveCue(id){const c=project().audio.musicCues.find(x=>x.id===id);if(!c)return;if(!['cleared','not-required'].includes(c.licenseStatus)){const cleared=confirm('该配乐的同步、商业使用和母带权利是否已经确认？');if(!cleared){toast('版权未确认，无法批准');return;}c.licenseStatus='cleared';}if(!c.filePath){toast('配乐 Cue 尚无音频文件，只能保持规划状态');return;}c.qaDecision='Approved';c.status='approved';save();render();toast(`${id} 已通过音乐 QA`);}

async function generateTtsTake(){const p=project(),a=p.audio,d=a.dialogues.find(x=>x.id===document.getElementById('ttsDialogue').value),button=document.getElementById('generateTts'),status=document.getElementById('ttsStatus');if(!d)return;if(!document.getElementById('ttsConfirmed').checked){toast('请先确认外部付费调用');return;}const voice=a.voices.find(v=>v.id===d.voiceId);if(voice?.sourceType==='clone'&&voice.consentStatus!=='consent-verified'){toast('声音克隆授权尚未验证');return;}button.disabled=true;button.textContent='生成中…';status.textContent='对白文本正在发送给 OpenAI；请不要关闭页面。';try{const response=await fetch('/api/audio/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:d.text,model:document.getElementById('ttsModel').value,voice:document.getElementById('ttsVoice').value,instructions:document.getElementById('ttsInstructions').value,speed:+document.getElementById('ttsSpeed').value,format:document.getElementById('ttsFormat').value,dialogue_id:d.id})});const result=await response.json().catch(()=>({error:'服务返回无法解析的响应'}));if(!response.ok)throw new Error(result.error||`生成失败（${response.status}）`);const id=nextAudioId(a.takes,'TAKE'),version=a.takes.filter(t=>t.dialogueId===d.id).length+1;a.takes.push({id,dialogueId:d.id,voiceId:d.voiceId,version,operation:'tts',filePath:result.url,duration:result.duration||null,provider:'openai',model:result.model,providerVoiceId:result.voice,format:result.format,settings:{instructions:document.getElementById('ttsInstructions').value,speed:+document.getElementById('ttsSpeed').value},sourceReferenceIds:[],qa:{decision:'Pending'},status:'generated-pending-qa',createdAt:new Date().toISOString()});save();render();toast(`${id} 已生成，等待 QA`);}catch(error){button.disabled=false;button.textContent='生成新 Take';status.textContent=error.message;status.classList.add('error');toast('配音生成失败');}}

function buildAudioHandoff(){const a=project().audio,refs=[],selected=a.dialogues.map(d=>a.takes.find(t=>t.id===d.selectedTakeId)).filter(audioApproved),music=a.musicCues.filter(audioApproved),sound=[...a.ambience,...a.soundEffects].filter(audioApproved);if(selected[0])refs.push({token:'@Audio1',assetId:selected[0].id,role:'批准对白的角色表演与时序'});if(music[0])refs.push({token:'@Audio2',assetId:music[0].id,role:'批准配乐的情绪与节奏'});if(sound[0])refs.push({token:'@Audio3',assetId:sound[0].id,role:'批准环境声或关键音效'});a.seedanceReferences=refs;save();render();toast(refs.length?'@Audio 映射已重建':'尚无可映射的批准音频');}
function audioPackagePayload(p){const a=ensureAudioModel(p);return {project_id:p.id,project_name:p.name,shot_timing_status:p.shots.length?'provisional':'missing',voices:a.voices.map(v=>({id:v.id,name:v.name,source_type:v.sourceType,provider:v.provider,model:v.model,provider_voice_id:v.providerVoiceId,language:v.language,dialect:v.dialect,voice_traits:String(v.traits||'').split(/[，,]/).filter(Boolean),reference_ids:v.referenceIds||[],consent_status:v.consentStatus,license_status:v.licenseStatus,status:v.status,file_path:v.filePath||''})),voice_references:a.voiceReferences.map(r=>({id:r.id,name:r.name,file_path:r.filePath,sha256:r.sha256,source_class:r.sourceClass,consent_status:r.consentStatus,status:r.status})),dialogues:a.dialogues.map(d=>({id:d.id,character_id:d.characterId,voice_id:d.voiceId,shot_ids:d.shotIds,text:d.text,language:d.language,emotion:d.emotion,intensity:d.intensity,pace:d.pace,target_duration:d.targetDuration,pronunciation:d.pronunciation,selected_take_id:d.selectedTakeId,status:d.status})),takes:a.takes.map(t=>({id:t.id,dialogue_id:t.dialogueId,voice_id:t.voiceId,version:t.version,operation:t.operation,file_path:t.filePath,duration:t.duration,provider:t.provider,model:t.model,provider_voice_id:t.providerVoiceId,format:t.format,settings:t.settings,source_reference_ids:t.sourceReferenceIds,qa:t.qa,status:t.status})),music_cues:a.musicCues.map(c=>({id:c.id,music_id:c.musicId,shot_ids:c.shotIds,start:c.start,end:c.end,purpose:c.purpose,entry:c.entry,exit:c.exit,dialogue_avoidance:c.dialogueAvoidance,loopable:c.loopable,file_path:c.filePath,license_status:c.licenseStatus,qa:{decision:c.qaDecision||'Pending'},status:c.status})),sound_effects:a.soundEffects,ambience:a.ambience,seedance_references:a.seedanceReferences.map(r=>({token:r.token,asset_id:r.assetId,role:r.role})),summary:audioSummary(p),exported_at:new Date().toISOString()};}
function exportAudioPackage(){const p=project();download(`${p.name.replace(/[\\/:*?"<>|]/g,'_')}.audio-package.json`,JSON.stringify(audioPackagePayload(p),null,2));toast('音频生产包已导出');}
